/*TASK1*/
CREATE DATABASE COMPANY;
USE COMPANY;
CREATE TABLE EMPLOYEES (
ID INT primary key identity,
[NAME] NVARCHAR(50) NOT NULL,
SURNAME NVARCHAR(50) NOT NULL,
POSITION NVARCHAR(50) NOT NULL,
SALARY DECIMAL (10,2)NOT NULL );

SELECT * FROM EMPLOYEES;

INSERT INTO EMPLOYEES ([NAME], SURNAME,POSITION, SALARY) VALUES 
('FARID', 'MAMMADOV', 'SENIOR INSPEKTOR', 2500),
('ULVI', 'MACIDOV', 'DEVELOPER-TEACHER',  4500),
('ELGUN', 'QULUZADE', 'HR', 3000),
('TURAL', 'CAVADOV', 'BUSINESS', 3500);

/*ORTALAMA MAASH*/
SELECT AVG( SALARY) AS ORTALAMA_MAAS FROM EMPLOYEES;

/*ORTALAMA MAASHDAN COX ALANLAR*/
SELECT * FROM EMPLOYEES WHERE SALARY>
(SELECT AVG(SALARY) AS ORTALAMA_MAAS FROM EMPLOYEES);

/*MAKSIMUM MAASH*/
SELECT MAX( SALARY) AS MAX_MAAS FROM EMPLOYEES;

/*MINUMUM MAASH*/
SELECT MIN( SALARY) AS MAX_MAAS FROM EMPLOYEES;

/*TASK2*/
CREATE DATABASE MARKET;
USE MARKET;
CREATE TABLE PRODUCTS (
ID INT primary key identity,
[NAME] NVARCHAR(50) NOT NULL,
PRICE DECIMAL (10,2)NOT NULL );

SELECT * FROM PRODUCTS;
/*BRAND SUTUNUN ELAVE EDIRIK*/
ALTER TABLE PRODUCTS ADD BRAND NVARCHAR(50);

/*DATA ELAVE EDILDI*/
INSERT INTO PRODUCTS ([NAME], BRAND, PRICE) VALUES 
('YAG', 'AZERSUN', 15),
('PENDIR', 'IVANOVKA',  3.50),
('SHOR', 'IVANOVKA', 3),
('QAYMAQ', 'BP',  3.50),
('ZEYTUN', 'ZT', 25),
('SU', 'SIRAB', 2.50),
('QAZLI SU', 'SIRAB',  3.50),
('SIRINIYYAT', 'VEYSELOGLE', 30),
('QAYMAQ', 'ZT',  11.50),
('ZEYTUN', 'ZT', 25),
('YUMURTA', 'KENDIMIZ', 0.20);

/*ORTALAMA QOIYMETDEN AZ QIYMETI OLANLAR*/
SELECT * FROM PRODUCTS WHERE PRICE < (SELECT AVG(PRICE) FROM PRODUCTS);

/*QIYMETI 10DAN COX OLANLAR*/
SELECT * FROM PRODUCTS WHERE PRICE>10;

/*BRAND UZUNLUGU 5 DEN BOYUK OLANLAR*/
SELECT [NAME] + ' ' + BRAND AS PRODUCTINFO, PRICE  FROM  (
SELECT *, LEN(BRAND) AS MEHSUL_AD_UZUNLUGU FROM PRODUCTS) PR WHERE MEHSUL_AD_UZUNLUGU >5;